export const JWT_SECRET_CONSTANT = 'JWT_SECRET_CONSTANT';
export const JWT_EXPIRES_ACCESS_TOKEN_CONSTANT = '168h'; //'12h';
export const JWT_EXPIRES_REFRESH_TOKEN_CONSTANT = '336h'; //'168h';
export const JWT_AES_TEXT_CONSTANT = 'JWT_AES_TEXT_CONSTANT';
