export {
  GetVersionRequestDto,
  GetTasksDto,
  GetTaskIdRequestDto,
  AddNewTaskRequestDto,
  UpdateTaskDto,
  DeleteTaskDto,
  UpdateTasksDto,
  DestroyTaskDto,
  RestoreTaskDto,
  GetTaskFeedsDto,
  GetTaskResponseDto,
  GetTasksResponseDto,
  UpdateTasksResponseDto,
  DeleteTasksResponseDto,
  GetTaskFeedsResponseDto,
} from './task.dto';
