export enum LocalizationMessage {
  INTERNAL_SERVER_ERROR = 'common.INTERNAL_SERVER_ERROR',
  POLICY_ENDPOINT_ERROR = 'common.POLICY_ENDPOINT_ERROR',

  TOO_MANY_REQUEST_ERROR = 'auth.TOO_MANY_REQUEST_ERROR',
  RESOURCE_FOTBIDDEN = 'auth.RESOURCE_FOTBIDDEN',

  VERIFY_CODE_CREATED = 'auth.VERIFY_CODE_CREATED',
  VERIFY_CODE_SIGN_UP = 'auth.VERIFY_CODE_SIGN_UP',
  VERIFY_CODE_ACCEPTED = 'auth.VERIFY_CODE_ACCEPTED',
  VERIFY_CODE_NOT_FOUND = 'auth.VERIFY_CODE_NOT_FOUND',
  VERIFY_CODE_COMPLETED = 'auth.VERIFY_CODE_COMPLETED',

  VERIFY_EMAIL = 'auth.VERIFY_EMAIL',

  REFRESH_TOKEN_UNAUTHORIZED = 'auth.REFRESH_TOKEN_UNAUTHORIZED',
  REFRESH_TOKEN_ACCEPTED = 'auth.REFRESH_TOKEN_ACCEPTED',

  UNAUTHORIZED = 'auth.UNAUTHORIZED',
  USER_BANNED = 'auth.USER_BANNED',

  VALIDATE_OBJECT_ID = 'common.VALIDATE.OBJECT_ID',

  EMAIL_NOT_REGISTERED = 'auth.EMAIL_NOT_REGISTERED',
  LOGIN_USERNAME_OR_PASSWORD_IS_INVALID = 'auth.LOGIN_USERNAME_OR_PASSWORD_IS_INVALID',
}
