export enum LocalizationMessage {
  INTERNAL_SERVER_ERROR = 'common.INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'common.VALIDATION_ERROR',
  VALIDATE_OBJECT_ID = 'common.VALIDATE.OBJECT_ID',

  GET_ONBOARDING_FEEDS = 'task.GET_ONBOARDING_FEEDS',
  GET_ONBOARDING_LIST = 'task.GET_LIST',
  GET_ONBOARDING_INFORMATION = 'task.GET_ONBOARDING_INFORMATION',
  GET_ONBOARDING_INFORMATION_SUCCESSFULLY = 'task.GET_ONBOARDING_INFORMATION_SUCCESSFULLY',
  CREATE_ONBOARDING_SUCCESSFULLY = 'task.CREATE_ONBOARDING_SUCCESSFULLY',
  UPDATING_ONBOARDING_SUCCESSFULLY = 'task.UPDATING_ONBOARDING_SUCCESSFULLY',
  DELETING_ONBOARDING_SUCCESSFULLY = 'task.DELETING_ONBOARDING_SUCCESSFULLY',
  UPDATING_ONBOARDING_ORDER_SUCCESSFULLY = 'task.UPDATING_ONBOARDING_ORDER_SUCCESSFULLY',
  ONBOARDING_ITEM_NOT_FOUND = 'task.ITEM_NOT_FOUND',
  ONBOARDING_ORDER_ITEM_NOT_FOUND = 'task.ORDER_ITEM_NOT_FOUND',
  ONBOARDING_ORDER_PLACE_NOT_VALID = 'task.ORDER_PLACE_NOT_VALID',
}
